In [32]:
import numpy as np

In [33]:
with open("pics2/vps1.csv") as f:
    vps = np.array([l.strip("\n").split(",") for l in f.readlines()]).astype("float")
vv1, vv2 = vps[:,:3], vps[:,3:]

In [34]:
def compute_ABCD_i(vpmi, vpni, vpm1, vpn1):
    u_mi, v_mi = vpmi[0], vpmi[1]
    u_ni, v_ni = vpni[0], vpni[1]
    u_m1, v_m1 = vpm1[0], vpm1[1]
    u_n1, v_n1 = vpn1[0], vpn1[1]
    
    A_i = u_mi - u_m1 + u_ni - u_n1
    B_i = v_mi - v_m1 + v_ni - v_n1
    C_i = v_m1*v_n1 - v_mi*v_ni
    D_i = u_mi*u_ni - u_m1*u_n1
    
    return A_i, B_i, C_i, D_i

In [35]:
A = []
b = []

for i in range(1,9):
    A_i, B_i, C_i, D_i = compute_ABCD_i(vv1[i], vv2[i], vv1[0], vv2[0])
    A += [[A_i, B_i, C_i]]
    b += [D_i]

a = np.linalg.lstsq(A, b,rcond=-1)
alpha = np.sqrt(a[0][2])
v_0 = a[0][1]/alpha
u_0=a[0][0]

In [36]:
alpha, v_0, u_0

(1.2847440118964129, -329.832583952195, 649.6175363760744)

In [39]:
f=0-((v_0-vv1[6][1])*(v_0-vv2[6][1]))-(1/a[0][2])*(vv1[6][0]-u_0)*(vv2[6][0]-u_0)

In [40]:
vv1[0], vv2[0], f

(array([ 4.03377304e+03, -1.03233832e+03,  1.00000000e+00]),
 array([-7.78844385e+02, -1.86022864e+03,  1.00000000e+00]),
 1823346.6261979938)

(array([ 3.20150216e+03, -2.35707346e+03,  2.46803149e+00]),
 array([], dtype=float64),
 3,
 array([1.17078919e+07, 2.25331832e+04, 4.24930316e+02]))