In [140]:
import numpy as np
import math

In [141]:
def middle(x1, y1, x2, y2):
    dx = x2 + x1
    dy = y2 + y1
    x=dx/2
    y=dy/2
    return (x,y)

In [142]:
def distance(x1, y1, x2, y2):
    dx=x2-x1
    dy=y2-y1
    dis=np.sqrt(dx*dx+dy*dy)
    
    return dis

In [143]:
with open("checkers_fullsize/outs.csv") as f:
    vps = np.array([l.strip("\n").split(",") for l in f.readlines()]).astype("float")
vv1, vv2 = vps[:,:3], vps[:,3:6]
vv1[:, 0:2] = vv1[:, 0:2]/3000
vv2[:, 0:2] = vv2[:, 0:2]/3000
index=[7,8,9,10]
vv1=vv1[index]
vv2=vv2[index]

In [144]:
A = []
b = []
for i in range(0,len(vv1)-1):
    x_i,y_i=middle(vv1[i][0],vv1[i][1],vv2[i][0],vv2[i][1])
    x_j,y_j=middle(vv1[i+1][0],vv1[i+1][1],vv2[i+1][0],vv2[i+1][1])
    r_i=distance(vv1[i][0],vv1[i][1],x_i,y_i)
    r_j=distance(vv1[i+1][0],vv1[i+1][1],x_j,y_j)
    A += [[ 2*(x_j-x_i),
                2*(y_j-y_i) ]]
    b += [ x_j*x_j-x_i*x_i+y_j*y_j-y_i*y_i+r_i*r_i-r_j*r_j]
w = np.linalg.lstsq(A, b)

/home/arnab/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  # This is added back by InteractiveShellApp.init_path()


In [145]:
pri=w[0]

In [146]:
f=r_j*r_j-(pri[0]-x_j)*(pri[0]-x_j)-(pri[1]-y_j)*(pri[1]-y_j)

In [147]:
np.sqrt(f)*3000

3129.0276507245544

In [148]:
pri*3000

array([1595.72974681, 1157.71015712])

In [149]:
v1=[vv1[0][0]-pri[0], vv1[0][1]-pri[1], -f]
v2=[vv2[0][0]-pri[0], vv2[0][1]-pri[1], -f]
np.dot(v1,v2)

0.044678313753337084

In [150]:
vv1,vv2,f, x_i

(array([[ -4.09668631,  -1.54042054,   1.        ],
        [ -4.16134302,  -1.5729721 ,   1.        ],
        [-10.43176422,  -2.83415697,   1.        ],
        [  7.44837643,  -0.19440548,   1.        ]]),
 array([[ 1.34772025, -0.9831694 ,  1.        ],
        [ 1.40270207, -1.12463247,  1.        ],
        [ 0.98633785, -0.82000751,  1.        ],
        [ 0.27203616, -0.83679021,  1.        ]]),
 1.0878682265554251,
 -4.722713180829263)

In [157]:
def length(v):
  return math.sqrt(np.dot(v, v))

In [159]:
math.acos(np.dot(v1, v2) / (length(v1) * length(v2)))

1.5662829316188032